### ISSUE TITLE
Footer copy is out of date

### ISSUE THREAD

**Issue by orta** [mennenia/mennenia.github.io#1]
Cant find the actual source, so this issue will do:

> Hi I’m Maxim :). I’m trying to get back into the habit of blogging by tinkering on this for the whole month of November 2015.

**Comment by orta** [comment]
Keep writing, the last one was great - sent it to DM

**Comment by mennenia** [comment]
Thanks! Issues are great :).

**Comment by mennenia** [comment]
Fixed
